apiVersion: v1
data:
  database_host: {{ default "127.0.0.1" .Values.database.host | b64enc | quote }}
  database_name: {{ default "tezauras" .Values.database.name | b64enc | quote }}
  database_password: {{ default "tezauras" .Values.database.password | b64enc | quote }}
  database_user: {{ default "tezauras" .Values.database.user | b64enc | quote }}
  facebook_app_id: {{ default "" .Values.facebook_app.id | b64enc | quote }}
  facebook_app_secret: {{ default "" .Values.facebook_app.secret | b64enc | quote }}
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
type: Opaque
